version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  gateway:
    build: 
      context: ./gateway-service/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - ./gateway-service/.env

  notification:
    build: 
      context: ./notification-service/
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - ./notification-service/.env

  user:
    build: 
      context: ./user-service/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    env_file:
      - ./user-service/.env

  schedule:
    build: 
      context: ./schedule-service/
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - ./schedule-service/.env